# Use the official Solr image from Docker Hub
FROM solr:9.2.1

# Create directories for custom configurations
USER root

RUN mkdir -p /var/solr/data
RUN chown -R solr:solr /var/solr

# Create directories with correct ownership
RUN mkdir -p /opt/solr/server/solr/configsets/deims2solr
RUN chown -R solr:solr /opt/solr/server/solr/configsets/deims2solr

# Copy Solr core configuration from local directory
COPY solr_config/* /opt/solr/server/solr/configsets/deims2solr

# Change ownership and permissions
RUN chown -R solr:solr /opt/solr/server/solr/configsets/deims2solr

# Switch back to solr user
USER solr

# Copy necessary jar files
COPY data-import-handler-9.2.1.jar /opt/solr/server/solr-webapp/webapp/WEB-INF/lib/
COPY postgresql-*.jar /opt/solr/server/solr-webapp/webapp/WEB-INF/lib/

# Expose Solr port
EXPOSE 8983

# Start Solr and create the core
CMD ["solr-precreate", "deims2solr", "/opt/solr/server/solr/configsets/deims2solr"]
